version: '3.8'
services:
  postgres:
    container_name: postgres
    build: ./src/dbScripts
    restart: always
    volumes:
      - ./dockerdata/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
